### ISSUE TITLE
Чему равен comvarSet[4] в самом начале игры?

### ISSUE THREAD

**Issue by ReenExe** [PavelOfficial/gridwars-bots#1]
Хочу сохранить данные откуда пришел шаг и получать эту информацию с текущей позиции [4]

**Comment by PavelOfficial** [comment]
В начале игры на первом ходе, comvarSet[4] равен "00000000000000000000000000000000". Исходя из общего принципа, что все новые ячейки имеют пустой comvar. Т.е. если в процессе хода было захвачено n ячеек, то они будут на следующем ходу иметь пустой комвар. И только после того, как ИИ отработает для этой ячейки хоть раз и установит для этой ячейки значение вернув его в 4ом аргументе возвращаемого ИИ массива. Это значение будет доступно на следующем ходу. Логично выделить хотя бы 1 бит на то, чтобы отличать новые ячейки от старых.

Вообще comvarSet[4] - это значение comvar текущей ячейки.

**Comment by ReenExe** [comment]
Значит после первого хода - я вижу исходную ячейку как "пустую" и захватываю ее повторно?

**Comment by PavelOfficial** [comment]
Подробно опишу первый ход:

Поступает comvarSet, где на 4ом индексе "00000000000000000000000000000000" и вокруг все пустые клетки, т.е. на всех остальных - 0 Numberom, как сигнал, что клетка не занята никем.

После отработки алгоритма возвращается 4ым элементом массива, тот comvar, что представит клетку эту, текущую на следующем ходу, например:  "00000000000000000000000000000001".

Начинается следующий ход:
Обработка этой же начальной клетки произойдет с comvarSet[4] === "00000000000000000000000000000001". И т.д для всех клеток ИИ.

> Значит после первого хода - я вижу исходную ячейку как "пустую" и захватываю ее повторно?

Нет после первого хода, т.е. на втором ходу есть возможность получить новое значение, что определено на первом ходу , как описано выше. Однако если вернуть 4ым элементном пустой comvar :  "00000000000000000000000000000000". То в этом случае тяжело будет определить чем второй ход будет отличаться от первого по комавру. Захват ячеек

**Comment by ReenExe** [comment]
Теперь стало понятно как делать логику
В начальный момент времени у меня поле
```javascript
var comvarSet = [
    Number(0), Number(0),                                  Number(0),
    Number(0), String('00000000000000000000000000000000'), Number(0),
    Number(0), Number(0),                                  Number(0)
];
```

**Comment by PavelOfficial** [comment]
Да. Может быть такой исход. 
Если первая клетка выстрелила все 3 вниз и вернула свой новый comvar '11101110111011101110111011101110'.
То второй comvarSet будет корректным для обработки вновь захваченной ячейки. Но так же на втором шаге будет вызов ИИ для начальной ячейки в таком случае будет вызван обработчик с comvarSet :
var comvarSet = [
    Number(0), Number(0), Number(0),
    Number(0), String('11101110111011101110111011101110') Number(0),
    Number(0), String('00000000000000000000000000000000'), Number(0)
];
Сколько ячеек под контролем ИИ - столько и вызовов для каждой и для каждого вызова свой актуальный comvarSet.
